language: go
sudo: false
go:
  - 1.8
  - 1.11

go_import_path: github.com/yvesago/dioc

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/gin-gonic/gin
  - go get github.com/mattn/go-sqlite3
  - go get github.com/stretchr/testify/assert
  - go get gopkg.in/gorp.v2
  - go get gopkg.in/gomail.v2
  - go get github.com/paulmach/go.geojson
  - go get github.com/oschwald/geoip2-golang
  - go get github.com/dgrijalva/jwt-go

script:
  - go test -v ./models/ -covermode=count -coverprofile=coverage.out

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken BIEo9NpDoOsOj4275L083xVyytZtR7oyM
