language: go
sudo: false
go:
  - 1.6
  - tip

script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/gin-gonic/gin
  - go get github.com/mattn/go-sqlite3
  - go get gopkg.in/gorp.v1
  - go get gopkg.in/gomail.v2
  - go test -v -covermode=count ./models/
